package com.bgremoval.CodeCafe.service;

import com.bgremoval.CodeCafe.dto.UploadResponse;
import org.springframework.web.multipart.MultipartFile;

import java.util.List;

/**
 * Accepts raw multipart file uploads, validates them, persists records, and
 * enqueues asynchronous background-removal processing.
 *
 * <p>Requirements: 1.1, 1.7, 2.1, 2.2, 3.3
 */
public interface UploadService {

    /**
     * Validates and enqueues each file for processing.
     *
     * <p>Files that pass {@link FileValidatorService} are stored as {@code IDLE}
     * {@code ImageRecord} objects and submitted to the async processing pool.
     * Files that fail validation are added to {@code rejectedFiles} in the
     * response but do not block processing of valid files.
     *
     * @param sessionId  caller-supplied session identifier (UUID generated by browser)
     * @param files      1–50 multipart files
     * @return {@link UploadResponse} containing accepted records and rejected filenames
     * @throws com.bgremoval.CodeCafe.exception.ValidationException if ALL
     *         submitted files fail validation or the list is empty
     */
    UploadResponse upload(String sessionId, List<MultipartFile> files);
}
